import type { Sql } from 'postgres';
import { ensureProviderId } from './pricing_pipeline.ts';

const STATIC_NETWORKING_PRICING = [
  // --- AWS ---
  { provider: 'aws', service: 'Data Transfer', category: 'Internet Egress', instance_type: 'First 10TB/month', price_per_unit: 0.09, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'First 10TB/month', destination: 'Internet', included_transfer: '100 GB/mo free', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'N/A', vpc_support: 'N/A', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'First 10TB', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'aws', service: 'Data Transfer', category: 'Internet Egress', instance_type: 'Next 40TB/month', price_per_unit: 0.085, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'Next 40TB/month', destination: 'Internet', included_transfer: 'None', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'N/A', vpc_support: 'N/A', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: '10TB - 50TB', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'aws', service: 'Data Transfer', category: 'Intra-Cloud Transfer', instance_type: 'Cross-AZ Transfer', price_per_unit: 0.01, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'Same Region (Different AZ)', included_transfer: 'None', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'N/A', vpc_support: 'Yes', transfer_direction: 'Intra-Cloud', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Cross-AZ' } },

  // Content Delivery Network
  { provider: 'aws', service: 'Content Delivery Network', category: 'Internet Egress', instance_type: 'First 10TB (North America)', price_per_unit: 0.085, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'First 10TB/month', destination: 'Internet', included_transfer: '1 TB/mo free', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'N/A', vpc_support: 'N/A', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'First 10TB', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'aws', service: 'Content Delivery Network', category: 'Internet Egress', instance_type: 'Next 40TB (North America)', price_per_unit: 0.080, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'Next 40TB/month', destination: 'Internet', included_transfer: 'None', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'N/A', vpc_support: 'N/A', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: '10TB - 50TB', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'gcp', service: 'Content Delivery Network', category: 'Internet Egress', instance_type: 'First 10TB (North America)', price_per_unit: 0.080, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'First 10TB/month', destination: 'Internet', included_transfer: 'None', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'N/A', vpc_support: 'N/A', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'First 10TB', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'azure', service: 'Content Delivery Network', category: 'Internet Egress', instance_type: 'First 10TB (North America)', price_per_unit: 0.081, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'First 10TB/month', destination: 'Internet', included_transfer: 'None', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'N/A', vpc_support: 'N/A', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'First 10TB', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'cloudflare', service: 'Content Delivery Network', category: 'Internet Egress', instance_type: 'Cloudflare Free', price_per_unit: 0.00, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'Unlimited', destination: 'Internet', included_transfer: 'Unlimited', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'Yes', vpc_support: 'N/A', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'Unlimited', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'cloudflare', service: 'Content Delivery Network', category: 'Internet Egress', instance_type: 'Cloudflare Pro', price_per_unit: 0.00, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'Unlimited', destination: 'Internet', included_transfer: 'Unlimited', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'Yes', vpc_support: 'N/A', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'Unlimited', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'aws', service: 'Public IPv4', category: 'IP Addresses', instance_type: 'Public IPv4 Address', price_per_unit: 0.005, unit: 'Hour', geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'N/A', included_transfer: 'None', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'N/A', vpc_support: 'N/A', transfer_direction: 'N/A', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'N/A' } },
  { provider: 'aws', service: 'Load Balancing', category: 'Application Load Balancer', instance_type: 'ALB Hourly', price_per_unit: 0.0225, unit: 'Hour', geography: 'N. America', attributes: { transfer_tier: 'Hourly Base', destination: 'N/A', included_transfer: 'None', connection_type: 'Multipoint', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Ingress', billing_model: 'Hourly Uptime', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'N/A' } },
  { provider: 'azure', service: 'Load Balancing', category: 'Standard Load Balancer', instance_type: 'Standard LB Hourly', price_per_unit: 0.025, unit: 'Hour', geography: 'N. America', attributes: { transfer_tier: 'Hourly Base', destination: 'N/A', included_transfer: 'None', connection_type: 'Multipoint', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Ingress', billing_model: 'Hourly Uptime', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'N/A' } },
  { provider: 'gcp', service: 'Load Balancing', category: 'Cloud Load Balancer', instance_type: 'Forwarding Rule Hourly', price_per_unit: 0.025, unit: 'Hour', geography: 'Global', attributes: { transfer_tier: 'Hourly Base', destination: 'N/A', included_transfer: 'None', connection_type: 'Multipoint', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Ingress', billing_model: 'Hourly Uptime', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'N/A' } },
  { provider: 'aws', service: 'Dedicated Connection', category: 'Direct Connect', instance_type: '1 Gbps Dedicated Port', price_per_unit: 0.30, unit: 'Hour', geography: 'N. America', attributes: { transfer_tier: 'Hourly Base', destination: 'On-Premises', included_transfer: 'None', connection_type: 'Point-to-Point', routing_type: 'Fixed', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'N/A', billing_model: 'Hourly Uptime', usage_tier: 'Flat Rate', port_capacity: '1 Gbps - 10 Gbps', transfer_scope: 'On-Premises' } },
  
  // API Gateways
  { provider: 'aws', service: 'API Gateway', category: 'REST API', instance_type: 'First 333 Million Requests', price_per_unit: 3.50, unit: '1M Requests', geography: 'N. America', attributes: { transfer_tier: 'Flat Rate', destination: 'Internet', included_transfer: '1M/mo free', connection_type: 'Multipoint', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Ingress', billing_model: 'Per Endpoint/Tunnel', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Internet' } },

  // --- Google Cloud ---
  { provider: 'gcp', service: 'Data Transfer', category: 'Internet Egress', instance_type: 'Premium Tier (0-10TB)', price_per_unit: 0.105, unit: 'GB', geography: 'Global', attributes: { transfer_tier: '0 - 10TB/month', destination: 'Internet', included_transfer: '200 GB/mo free', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'N/A', vpc_support: 'N/A', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'First 10TB', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'gcp', service: 'Data Transfer', category: 'Internet Egress', instance_type: 'Standard Tier', price_per_unit: 0.085, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'Internet', included_transfer: '200 GB/mo free', connection_type: 'N/A', routing_type: 'Fixed', ha_support: 'N/A', vpc_support: 'N/A', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'gcp', service: 'Data Transfer', category: 'Intra-Cloud Transfer', instance_type: 'Cross-AZ Transfer', price_per_unit: 0.01, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'Same Region (Different AZ)', included_transfer: 'None', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'N/A', vpc_support: 'Yes', transfer_direction: 'Intra-Cloud', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Cross-AZ' } },
  { provider: 'gcp', service: 'Dedicated Connection', category: 'Cloud Interconnect', instance_type: '10 Gbps Dedicated Interconnect', price_per_unit: 1.70, unit: 'Hour', geography: 'Global', attributes: { transfer_tier: 'Hourly Base', destination: 'On-Premises', included_transfer: 'None', connection_type: 'Point-to-Point', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'N/A', billing_model: 'Hourly Uptime', usage_tier: 'Flat Rate', port_capacity: '1 Gbps - 10 Gbps', transfer_scope: 'On-Premises' } },
  { provider: 'gcp', service: 'API Gateway', category: 'API Calls', instance_type: '0-2 Million API Calls', price_per_unit: 3.00, unit: '1M Requests', geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'Internet', included_transfer: '2M/mo free', connection_type: 'Multipoint', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Ingress', billing_model: 'Per Endpoint/Tunnel', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Internet' } },

  // --- Azure ---
  { provider: 'azure', service: 'Data Transfer', category: 'Internet Egress', instance_type: 'First 10TB/month', price_per_unit: 0.087, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'First 10TB/month', destination: 'Internet', included_transfer: '100 GB/mo free', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'N/A', vpc_support: 'N/A', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'First 10TB', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'azure', service: 'Data Transfer', category: 'Intra-Cloud Transfer', instance_type: 'Cross-AZ Transfer', price_per_unit: 0.01, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'Same Region (Different AZ)', included_transfer: 'None', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'N/A', vpc_support: 'Yes', transfer_direction: 'Intra-Cloud', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Cross-AZ' } },
  { provider: 'azure', service: 'Virtual Private Cloud', category: 'VNet Peering', instance_type: 'Intra-Region Peering', price_per_unit: 0.01, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'Same Region (VNet to VNet)', included_transfer: 'None', connection_type: 'Point-to-Point', routing_type: 'Fixed', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Intra-Cloud', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Same Region' } },
  { provider: 'azure', service: 'Dedicated Connection', category: 'ExpressRoute', instance_type: '1 Gbps Direct Port', price_per_unit: 0.40, unit: 'Hour', geography: 'Global', attributes: { transfer_tier: 'Hourly Base', destination: 'On-Premises', included_transfer: 'None', connection_type: 'Point-to-Point', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'N/A', billing_model: 'Hourly Uptime', usage_tier: 'Flat Rate', port_capacity: '1 Gbps - 10 Gbps', transfer_scope: 'On-Premises' } },
  { provider: 'azure', service: 'API Gateway', category: 'API Management', instance_type: 'Consumption Tier', price_per_unit: 3.50, unit: '1M Requests', geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'Internet', included_transfer: '1M/mo free', connection_type: 'Multipoint', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Ingress', billing_model: 'Per Endpoint/Tunnel', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Internet' } },

  // --- Oracle ---
  { provider: 'oracle', service: 'Data Transfer', category: 'Internet Egress', instance_type: 'Outbound Data Transfer', price_per_unit: 0.0085, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'Over 10TB/month', destination: 'Internet', included_transfer: '10 TB/mo free', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'N/A', vpc_support: 'N/A', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'Over 10TB', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'oracle', service: 'Data Transfer', category: 'Intra-Cloud Transfer', instance_type: 'Cross-AD Transfer', price_per_unit: 0.01, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'Same Region (Different AD)', included_transfer: 'None', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'N/A', vpc_support: 'Yes', transfer_direction: 'Intra-Cloud', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Cross-AZ' } },
  { provider: 'oracle', service: 'Load Balancing', category: 'Flexible Load Balancer', instance_type: 'Base Rate (10 Mbps)', price_per_unit: 0.0113, unit: 'Hour', geography: 'Global', attributes: { transfer_tier: 'Base', destination: 'N/A', included_transfer: 'None', connection_type: 'Multipoint', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Ingress', billing_model: 'Hourly Uptime', usage_tier: 'Flat Rate', port_capacity: '< 1 Gbps', transfer_scope: 'N/A' } },
  { provider: 'oracle', service: 'Dedicated Connection', category: 'FastConnect', instance_type: '1 Gbps Port', price_per_unit: 0.20, unit: 'Hour', geography: 'Global', attributes: { transfer_tier: 'Hourly Base', destination: 'On-Premises', included_transfer: 'None', connection_type: 'Point-to-Point', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'N/A', billing_model: 'Hourly Uptime', usage_tier: 'Flat Rate', port_capacity: '1 Gbps - 10 Gbps', transfer_scope: 'On-Premises' } },

  // --- DigitalOcean ---
  { provider: 'digitalocean', service: 'Data Transfer', category: 'Internet Egress', instance_type: 'Overage (Post-Allowance)', price_per_unit: 0.01, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'Over Allowance', destination: 'Internet', included_transfer: '1TB - 11TB/mo free', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'N/A', vpc_support: 'N/A', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'Over Allowance', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'digitalocean', service: 'Virtual Private Cloud', category: 'Internal VPC Transfer', instance_type: 'VPC Transfer', price_per_unit: 0, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'Same Region (Internal VPC)', included_transfer: 'Unlimited', connection_type: 'Multipoint', routing_type: 'Fixed', ha_support: 'No', vpc_support: 'Yes', transfer_direction: 'Intra-Cloud', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Same Region' } },
  { provider: 'digitalocean', service: 'Load Balancing', category: 'Managed Load Balancer', instance_type: 'Small (1 Node)', price_per_unit: 0.01785, unit: 'Hour', geography: 'Global', attributes: { transfer_tier: 'Base Rate', destination: 'N/A', included_transfer: '10', connection_type: 'Multipoint', routing_type: 'Fixed', ha_support: 'Yes', vpc_support: 'No', transfer_direction: 'Ingress', billing_model: 'Hourly Uptime', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'N/A' } },

  // --- Alibaba ---
  { provider: 'alibaba', service: 'Data Transfer', category: 'Internet Egress', instance_type: 'Pay-By-Traffic', price_per_unit: 0.08, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'Internet', included_transfer: 'None', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'N/A', vpc_support: 'N/A', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'alibaba', service: 'Data Transfer', category: 'Intra-Cloud Transfer', instance_type: 'Cross-AZ Transfer', price_per_unit: 0.01, unit: 'GB', geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'Same Region (Different AZ)', included_transfer: 'None', connection_type: 'N/A', routing_type: 'N/A', ha_support: 'N/A', vpc_support: 'Yes', transfer_direction: 'Intra-Cloud', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Cross-AZ' } },
  { provider: 'alibaba', service: 'Load Balancing', category: 'Server Load Balancer', instance_type: 'SLB Hourly', price_per_unit: 0.02, unit: 'Hour', geography: 'Global', attributes: { transfer_tier: 'Base', destination: 'N/A', included_transfer: 'None', connection_type: 'Multipoint', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Ingress', billing_model: 'Hourly Uptime', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'N/A' } },
  { provider: 'alibaba', service: 'Public IPv4', category: 'Elastic IP', instance_type: 'EIP (In Use)', price_per_unit: 0.005, unit: 'Hour', geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'N/A', included_transfer: 'None', connection_type: 'Point-to-Point', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'N/A', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'N/A' } },

  // ─── Cross-Region Transfer ───────────────────────────────────────────────────
  { provider: 'aws',          service: 'Data Transfer', category: 'Cross-Region Transfer', instance_type: 'Cross-Region (US)',              price_per_unit: 0.02,   unit: 'GB',   geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'Different AWS Region', included_transfer: 'None', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'N/A', vpc_support: 'Yes', transfer_direction: 'Intra-Cloud', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Cross-Region' } },
  { provider: 'gcp',          service: 'Data Transfer', category: 'Cross-Region Transfer', instance_type: 'Inter-Region (Same Continent)', price_per_unit: 0.01,   unit: 'GB',   geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'Different GCP Region', included_transfer: 'None', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'N/A', vpc_support: 'Yes', transfer_direction: 'Intra-Cloud', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Cross-Region' } },
  { provider: 'azure',        service: 'Data Transfer', category: 'Cross-Region Transfer', instance_type: 'Cross-Region (Same Geography)', price_per_unit: 0.02,   unit: 'GB',   geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'Different Azure Region', included_transfer: 'None', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'N/A', vpc_support: 'Yes', transfer_direction: 'Intra-Cloud', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Cross-Region' } },
  { provider: 'oracle',       service: 'Data Transfer', category: 'Cross-Region Transfer', instance_type: 'Cross-Region Transfer',         price_per_unit: 0.0085, unit: 'GB',   geography: 'Global', attributes: { transfer_tier: 'Over 10TB/month', destination: 'Different OCI Region', included_transfer: '10 TB/mo free', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'N/A', vpc_support: 'Yes', transfer_direction: 'Intra-Cloud', billing_model: 'Data Processed (GB)', usage_tier: 'Over 10TB', port_capacity: 'N/A', transfer_scope: 'Cross-Region' } },
  { provider: 'digitalocean', service: 'Data Transfer', category: 'Cross-Region Transfer', instance_type: 'Cross-Datacenter Transfer',     price_per_unit: 0.01,   unit: 'GB',   geography: 'Global', attributes: { transfer_tier: 'Over Allowance', destination: 'Different DigitalOcean Datacenter', included_transfer: 'Shared with Droplet allowance', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'N/A', vpc_support: 'No', transfer_direction: 'Intra-Cloud', billing_model: 'Data Processed (GB)', usage_tier: 'Over Allowance', port_capacity: 'N/A', transfer_scope: 'Cross-Region' } },
  { provider: 'alibaba',      service: 'Data Transfer', category: 'Cross-Region Transfer', instance_type: 'Cross-Region (CEN)',            price_per_unit: 0.0125, unit: 'GB',   geography: 'Global', attributes: { transfer_tier: 'Flat Rate', destination: 'Different Alibaba Region', included_transfer: 'None', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'N/A', vpc_support: 'Yes', transfer_direction: 'Intra-Cloud', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Cross-Region' } },

  // ─── NAT Gateways ────────────────────────────────────────────────────────────
  { provider: 'aws',    service: 'NAT Gateway', category: 'NAT Gateway', instance_type: 'NAT Gateway (Hourly)',        price_per_unit: 0.045,  unit: 'Hour', geography: 'N. America', attributes: { transfer_tier: 'Hourly Base', destination: 'N/A', included_transfer: 'None', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Egress', billing_model: 'Hourly Uptime', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'N/A' } },
  { provider: 'aws',    service: 'NAT Gateway', category: 'NAT Gateway', instance_type: 'NAT Gateway (Data)',         price_per_unit: 0.045,  unit: 'GB',   geography: 'N. America', attributes: { transfer_tier: 'Flat Rate', destination: 'Internet', included_transfer: 'None', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'gcp',    service: 'NAT Gateway', category: 'NAT Gateway', instance_type: 'Cloud NAT (Per Endpoint)',  price_per_unit: 0.0044, unit: 'Hour', geography: 'Global',  attributes: { transfer_tier: 'Per NAT IP', destination: 'N/A', included_transfer: 'None', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Egress', billing_model: 'Per Endpoint/Tunnel', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'N/A' } },
  { provider: 'gcp',    service: 'NAT Gateway', category: 'NAT Gateway', instance_type: 'Cloud NAT (Data)',          price_per_unit: 0.045,  unit: 'GB',   geography: 'Global',  attributes: { transfer_tier: 'Flat Rate', destination: 'Internet', included_transfer: 'None', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'azure',  service: 'NAT Gateway', category: 'NAT Gateway', instance_type: 'NAT Gateway (Hourly)',      price_per_unit: 0.045,  unit: 'Hour', geography: 'N. America', attributes: { transfer_tier: 'Hourly Base', destination: 'N/A', included_transfer: 'None', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Egress', billing_model: 'Hourly Uptime', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'N/A' } },
  { provider: 'azure',  service: 'NAT Gateway', category: 'NAT Gateway', instance_type: 'NAT Gateway (Data)',        price_per_unit: 0.045,  unit: 'GB',   geography: 'N. America', attributes: { transfer_tier: 'Flat Rate', destination: 'Internet', included_transfer: 'None', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Internet' } },
  { provider: 'oracle', service: 'NAT Gateway', category: 'NAT Gateway', instance_type: 'NAT Gateway (Included)',   price_per_unit: 0.00,   unit: 'Hour', geography: 'Global',  attributes: { transfer_tier: 'Included', destination: 'N/A', included_transfer: 'Included', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Egress', billing_model: 'Included', usage_tier: 'Included', port_capacity: 'N/A', transfer_scope: 'N/A' } },
  { provider: 'alibaba', service: 'NAT Gateway', category: 'NAT Gateway', instance_type: 'Enhanced NAT (Small)',    price_per_unit: 0.017,  unit: 'Hour', geography: 'Global',  attributes: { transfer_tier: 'Hourly Base', destination: 'N/A', included_transfer: 'None', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Egress', billing_model: 'Hourly Uptime', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'N/A' } },
  { provider: 'alibaba', service: 'NAT Gateway', category: 'NAT Gateway', instance_type: 'Enhanced NAT (Data)',     price_per_unit: 0.045,  unit: 'GB',   geography: 'Global',  attributes: { transfer_tier: 'Flat Rate', destination: 'Internet', included_transfer: 'None', connection_type: 'N/A', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'Internet' } },

  // ─── VPN Gateways ────────────────────────────────────────────────────────────
  { provider: 'aws',    service: 'VPN Gateway', category: 'Site-to-Site VPN', instance_type: 'VPN Connection (Hourly)',  price_per_unit: 0.05,   unit: 'Hour', geography: 'N. America', attributes: { transfer_tier: 'Per Tunnel', destination: 'On-Premises', included_transfer: 'None', connection_type: 'Point-to-Point', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'N/A', billing_model: 'Per Endpoint/Tunnel', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'On-Premises' } },
  { provider: 'aws',    service: 'VPN Gateway', category: 'Site-to-Site VPN', instance_type: 'VPN Data Transfer',       price_per_unit: 0.048,  unit: 'GB',   geography: 'N. America', attributes: { transfer_tier: 'Flat Rate', destination: 'On-Premises', included_transfer: 'None', connection_type: 'Point-to-Point', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'Egress', billing_model: 'Data Processed (GB)', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'On-Premises' } },
  { provider: 'gcp',    service: 'VPN Gateway', category: 'Cloud VPN',        instance_type: 'VPN Tunnel (Hourly)',     price_per_unit: 0.05,   unit: 'Hour', geography: 'Global',  attributes: { transfer_tier: 'Per Tunnel', destination: 'On-Premises', included_transfer: 'None', connection_type: 'Point-to-Point', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'N/A', billing_model: 'Per Endpoint/Tunnel', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'On-Premises' } },
  { provider: 'azure',  service: 'VPN Gateway', category: 'VPN Gateway',      instance_type: 'VpnGw1 (Hourly)',        price_per_unit: 0.19,   unit: 'Hour', geography: 'N. America', attributes: { transfer_tier: 'Hourly Base', destination: 'On-Premises', included_transfer: 'None', connection_type: 'Point-to-Point', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'N/A', billing_model: 'Hourly Uptime', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'On-Premises' } },
  { provider: 'oracle', service: 'VPN Gateway', category: 'VPN Connect',      instance_type: 'IPSec Tunnel (Hourly)',   price_per_unit: 0.0085, unit: 'Hour', geography: 'Global',  attributes: { transfer_tier: 'Per Tunnel', destination: 'On-Premises', included_transfer: '2 tunnels/mo free', connection_type: 'Point-to-Point', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'N/A', billing_model: 'Per Endpoint/Tunnel', usage_tier: 'Flat Rate', port_capacity: 'N/A', transfer_scope: 'On-Premises' } },
  { provider: 'alibaba', service: 'VPN Gateway', category: 'VPN Gateway',     instance_type: 'VPN Gateway (5 Mbps)',   price_per_unit: 0.052,  unit: 'Hour', geography: 'Global',  attributes: { transfer_tier: 'Hourly Base', destination: 'On-Premises', included_transfer: 'None', connection_type: 'Point-to-Point', routing_type: 'Dynamic', ha_support: 'Yes', vpc_support: 'Yes', transfer_direction: 'N/A', billing_model: 'Hourly Uptime', usage_tier: 'Flat Rate', port_capacity: '< 1 Gbps', transfer_scope: 'On-Premises' } },
];

export class NetworkingPricingPipeline {
  private sql: Sql;

  constructor(sql: Sql) {
    this.sql = sql;
  }

  
  async run() {
    console.log('🚀 Starting Networking Pricing Pipeline...');
    const results: any[] = [];

    // Ensure services exist
    await this.setupNetworkingServices();

    let recordsAdded = 0;

    await this.sql.begin(async (sql) => {
      // Clear existing static networking data to avoid duplicates
      await sql`
        DELETE FROM pricing_records 
        WHERE data_source = 'static_config' 
        AND service_id IN (
          SELECT id FROM services WHERE category = 'networking'
        )
      `;

      for (const record of STATIC_NETWORKING_PRICING) {
        // Resolve provider id, auto-creating from config if not yet seeded.
        const providerId = await ensureProviderId(sql, record.provider);

        let serviceRes = await sql`SELECT id FROM services WHERE provider_id = ${providerId} AND name = ${record.service} AND category = 'networking'`;
        let serviceId: string;

        if (serviceRes.length === 0) {
          const insertService = await sql`
            INSERT INTO services (provider_id, name, category) VALUES (${providerId}, ${record.service}, 'networking') RETURNING id
          `;
          serviceId = insertService[0].id;
        } else {
          serviceId = serviceRes[0].id;
        }

        // Insert pricing record
        await sql`
          INSERT INTO pricing_records 
            (service_id, instance_type, category, geography, price_per_unit, unit, attributes, data_source, updated_at) 
           VALUES (
             ${serviceId}, ${record.instance_type}, ${record.category}, ${record.geography}, 
             ${record.price_per_unit}, ${record.unit}, ${sql.json(record.attributes)}, 
             'static_config', NOW()
           )
        `;
        recordsAdded++;
      }
    });

    results.push({ provider: 'all_networking', status: 'success', recordsProcessed: recordsAdded });
    console.log(`✅ Networking Pricing Pipeline Completed. Inserted ${recordsAdded} records.`);
    return results;
  }

  private async setupNetworkingServices() {
    const services = ['Data Transfer', 'Content Delivery Network', 'Virtual Private Cloud', 'Load Balancing', 'Dedicated Connection', 'Public IPv4', 'NAT Gateway', 'VPN Gateway'];
    for (const service of services) {
      await this.sql`
        INSERT INTO services (provider_id, name, category)
        SELECT id, ${service}, 'networking' FROM providers WHERE slug IN ('aws', 'gcp', 'azure', 'oracle', 'digitalocean', 'alibaba')
        ON CONFLICT (provider_id, name) DO UPDATE SET category = 'networking'
      `;
    }
  }

}
