export interface AIModelConfig {
  providerSlug: string;
  serviceName: string;
  regionSlug?: string;
  geography: string;
  modelName: string;
  inputPricePer1M: number;
  outputPricePer1M?: number;
  contextWindowK?: number;
  modelTier: string; // Capability tier: Frontier, Standard, Efficient.
  modality: string; // Model type/use case: Chat, Coding, Embedding, Reranking, Image, Audio, Reasoning.
  multimodal: string;
  trainingCutoff?: string;
}

// All prices are on-demand (pay-as-you-go) in USD per 1M tokens.
//
// IMPORTANT — this file is a hand-maintained static list, not a scraped/live
// pipeline (see src/services/ai_pipeline.ts). Every other category on this
// site (VMs, storage, containers, etc.) pulls from a real scraper hitting the
// provider's API; AI model pricing does not, which means this list will
// silently drift as providers add/retire models. Treat additions here as a
// stopgap — the durable fix is a real ingestion pipeline per provider
// (Bedrock model catalog + pricing API, Azure AI Foundry catalog, etc.).
//
// Sources (fetched June 2026, updated July 2026 to add previously-missing
// third-party models on Bedrock and Azure AI Foundry — see CCC/Web/MEMORY.md):
//   OpenAI    — developers.openai.com/api/docs/models
//   Anthropic — platform.claude.com/docs/en/about-claude/pricing
//   GCP       — cloud.google.com/vertex-ai/generative-ai/pricing
//   Bedrock   — aws.amazon.com/bedrock/pricing/ (Nova, DeepSeek-R1, Mistral Large 2 added Jul 2026)
//   Azure     — azure.microsoft.com/pricing/details/ai-foundry-models/ (DeepSeek-R1, Llama added Jul 2026 — Azure AI Foundry sells far more than OpenAI models)

export const AI_MODELS: AIModelConfig[] = [

  // ── Radium (radium.cloud/pricing, added 2026-07-29) ─────────────────────
  {
    providerSlug: 'radium',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Hal 1.0',
    inputPricePer1M: 2.75,
    outputPricePer1M: 11.50,
    modelTier: 'Frontier',
    modality: 'Chat',
    multimodal: 'No',
  },
  {
    providerSlug: 'radium',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Clarke 1.0',
    inputPricePer1M: 1.50,
    outputPricePer1M: 7.00,
    modelTier: 'Standard',
    modality: 'Chat',
    multimodal: 'No',
  },
  {
    providerSlug: 'radium',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Tycho 1.0',
    inputPricePer1M: 0.50,
    outputPricePer1M: 2.25,
    modelTier: 'Efficient',
    modality: 'Chat',
    multimodal: 'No',
  },

  // ── OpenAI ────────────────────────────────────────────────────────────
  {
    providerSlug: 'openai',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'GPT-5.5',
    inputPricePer1M: 5.00,
    outputPricePer1M: 30.00,
    contextWindowK: 128,
    modelTier: 'Frontier',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'openai',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'GPT-5.4',
    inputPricePer1M: 2.50,
    outputPricePer1M: 15.00,
    contextWindowK: 128,
    modelTier: 'Standard',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'openai',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'GPT-5.4 mini',
    inputPricePer1M: 0.75,
    outputPricePer1M: 4.50,
    contextWindowK: 128,
    modelTier: 'Efficient',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'openai',
    serviceName: 'Embeddings',
    geography: 'Global',
    modelName: 'text-embedding-3-large',
    inputPricePer1M: 0.13,
    modelTier: 'Standard',
    modality: 'Embedding',
    multimodal: 'No',
  },

  // ── Anthropic ─────────────────────────────────────────────────────────
  {
    providerSlug: 'anthropic',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Claude Opus 4.8',
    inputPricePer1M: 5.00,
    outputPricePer1M: 25.00,
    contextWindowK: 1000,
    modelTier: 'Frontier',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'anthropic',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Claude Sonnet 4.6',
    inputPricePer1M: 3.00,
    outputPricePer1M: 15.00,
    contextWindowK: 1000,
    modelTier: 'Standard',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'anthropic',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Claude Haiku 4.5',
    inputPricePer1M: 1.00,
    outputPricePer1M: 5.00,
    contextWindowK: 200,
    modelTier: 'Efficient',
    modality: 'Chat',
    multimodal: 'Yes',
  },

  // ── Google Vertex AI ──────────────────────────────────────────────────
  {
    providerSlug: 'gcp',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Gemini 2.5 Pro',
    inputPricePer1M: 1.25,
    outputPricePer1M: 10.00,
    contextWindowK: 1000,
    modelTier: 'Frontier',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'gcp',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Gemini 2.5 Flash',
    inputPricePer1M: 0.30,
    outputPricePer1M: 2.50,
    contextWindowK: 1000,
    modelTier: 'Standard',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'gcp',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Gemini 2.0 Flash',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.60,
    contextWindowK: 1000,
    modelTier: 'Efficient',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'gcp',
    serviceName: 'Embeddings',
    geography: 'Global',
    modelName: 'text-embedding-005',
    inputPricePer1M: 0.025,
    modelTier: 'Standard',
    modality: 'Embedding',
    multimodal: 'No',
  },

  // ── AWS Bedrock ───────────────────────────────────────────────────────
  {
    providerSlug: 'aws',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Claude Sonnet 4.6 (Bedrock)',
    inputPricePer1M: 3.00,
    outputPricePer1M: 15.00,
    contextWindowK: 1000,
    modelTier: 'Standard',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'aws',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Llama 4 Maverick (Bedrock)',
    inputPricePer1M: 0.24,
    outputPricePer1M: 0.97,
    contextWindowK: 1000,
    modelTier: 'Efficient',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'aws',
    serviceName: 'Embeddings',
    geography: 'Global',
    modelName: 'Titan Text Embeddings V2 (Bedrock)',
    inputPricePer1M: 0.02,
    modelTier: 'Standard',
    modality: 'Embedding',
    multimodal: 'No',
  },
  {
    providerSlug: 'aws',
    serviceName: 'Embeddings',
    geography: 'Global',
    modelName: 'Cohere Embed English v3 (Bedrock)',
    inputPricePer1M: 0.10,
    modelTier: 'Standard',
    modality: 'Embedding',
    multimodal: 'No',
  },
  // Amazon's own Nova family, added to close the gap where only third-party
  // models were represented for Bedrock.
  {
    providerSlug: 'aws',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Amazon Nova Pro (Bedrock)',
    inputPricePer1M: 0.80,
    outputPricePer1M: 3.20,
    contextWindowK: 300,
    modelTier: 'Standard',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'aws',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Amazon Nova Lite (Bedrock)',
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.24,
    contextWindowK: 300,
    modelTier: 'Efficient',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'aws',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Amazon Nova Micro (Bedrock)',
    inputPricePer1M: 0.035,
    outputPricePer1M: 0.14,
    contextWindowK: 128,
    modelTier: 'Efficient',
    modality: 'Chat',
    multimodal: 'No',
  },
  // DeepSeek — flagged by Rodrigo as a known gap; DeepSeek-R1 is available
  // via Bedrock Marketplace.
  {
    providerSlug: 'aws',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'DeepSeek-R1 (Bedrock)',
    inputPricePer1M: 1.35,
    outputPricePer1M: 5.40,
    contextWindowK: 128,
    modelTier: 'Standard',
    modality: 'Reasoning',
    multimodal: 'No',
  },
  {
    providerSlug: 'aws',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Mistral Large 2 (Bedrock)',
    inputPricePer1M: 3.00,
    outputPricePer1M: 9.00,
    contextWindowK: 128,
    modelTier: 'Standard',
    modality: 'Chat',
    multimodal: 'No',
  },

  // ── Azure (Microsoft Foundry) ─────────────────────────────────────────
  {
    providerSlug: 'azure',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'GPT-5.5 (Azure)',
    inputPricePer1M: 5.00,
    outputPricePer1M: 30.00,
    contextWindowK: 128,
    modelTier: 'Frontier',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'azure',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'GPT-5.4 (Azure)',
    inputPricePer1M: 2.50,
    outputPricePer1M: 15.00,
    contextWindowK: 128,
    modelTier: 'Standard',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'azure',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'GPT-5.4 mini (Azure)',
    inputPricePer1M: 0.75,
    outputPricePer1M: 4.50,
    contextWindowK: 128,
    modelTier: 'Efficient',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'azure',
    serviceName: 'Embeddings',
    geography: 'Global',
    modelName: 'text-embedding-3-large (Azure)',
    inputPricePer1M: 0.13,
    modelTier: 'Standard',
    modality: 'Embedding',
    multimodal: 'No',
  },
  {
    providerSlug: 'azure',
    serviceName: 'Embeddings',
    geography: 'Global',
    modelName: 'text-embedding-3-small (Azure)',
    inputPricePer1M: 0.02,
    modelTier: 'Standard',
    modality: 'Embedding',
    multimodal: 'No',
  },
  // Azure AI Foundry's model catalog goes well beyond OpenAI — DeepSeek,
  // Llama, and Mistral are all sold directly by Azure. Previously missing
  // entirely, which made Azure look like an OpenAI-only reseller.
  {
    providerSlug: 'azure',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'DeepSeek-R1 (Azure AI Foundry)',
    inputPricePer1M: 1.14,
    outputPricePer1M: 4.56,
    contextWindowK: 128,
    modelTier: 'Standard',
    modality: 'Reasoning',
    multimodal: 'No',
  },
  {
    providerSlug: 'azure',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Llama 4 Maverick (Azure AI Foundry)',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.60,
    contextWindowK: 1000,
    modelTier: 'Efficient',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'azure',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Llama 3.3 70B (Azure AI Foundry)',
    inputPricePer1M: 0.59,
    outputPricePer1M: 0.79,
    contextWindowK: 128,
    modelTier: 'Standard',
    modality: 'Chat',
    multimodal: 'No',
  },

  // ── Oracle (OCI Generative AI) ──────────────────────────────────────────
  {
    providerSlug: 'oracle',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Cohere Command R+',
    inputPricePer1M: 3.00,
    outputPricePer1M: 15.00,
    contextWindowK: 128,
    modelTier: 'Frontier',
    modality: 'Chat',
    multimodal: 'No',
  },
  {
    providerSlug: 'oracle',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Cohere Command R',
    inputPricePer1M: 0.50,
    outputPricePer1M: 1.50,
    contextWindowK: 128,
    modelTier: 'Standard',
    modality: 'Chat',
    multimodal: 'No',
  },
  {
    providerSlug: 'oracle',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Meta Llama 3 70B',
    inputPricePer1M: 0.75,
    outputPricePer1M: 0.75,
    contextWindowK: 8,
    modelTier: 'Efficient',
    modality: 'Chat',
    multimodal: 'No',
  },
  {
    // OCI GenAI prices embeddings at $0.001 per 10k transactions (1 char = 1
    // transaction); at ~4 chars/token that's ≈ $0.40 per 1M tokens. Added
    // because Oracle showed N/A on Embeddings components despite offering
    // Cohere Embed on OCI Generative AI.
    providerSlug: 'oracle',
    serviceName: 'Embeddings',
    geography: 'Global',
    modelName: 'Cohere Embed 3 (OCI GenAI)',
    inputPricePer1M: 0.40,
    modelTier: 'Standard',
    modality: 'Embedding',
    multimodal: 'No',
  },

  // ── DigitalOcean (GenAI Platform) ───────────────────────────────────────
  {
    providerSlug: 'digitalocean',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Anthropic Claude Opus 4.8',
    inputPricePer1M: 5.00,
    outputPricePer1M: 25.00,
    contextWindowK: 1000,
    modelTier: 'Frontier',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'digitalocean',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Anthropic Claude Sonnet 4.6',
    inputPricePer1M: 3.00,
    outputPricePer1M: 15.00,
    contextWindowK: 1000,
    modelTier: 'Standard',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'digitalocean',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Anthropic Claude Haiku 4.5',
    inputPricePer1M: 1.00,
    outputPricePer1M: 5.00,
    contextWindowK: 200,
    modelTier: 'Efficient',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'digitalocean',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Meta Llama 3 70B Instruct',
    inputPricePer1M: 0.70,
    outputPricePer1M: 0.90,
    contextWindowK: 8,
    modelTier: 'Standard',
    modality: 'Chat',
    multimodal: 'No',
  },
  {
    providerSlug: 'digitalocean',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Meta Llama 3 8B Instruct',
    inputPricePer1M: 0.10,
    outputPricePer1M: 0.20,
    contextWindowK: 8,
    modelTier: 'Efficient',
    modality: 'Chat',
    multimodal: 'No',
  },
  {
    providerSlug: 'digitalocean',
    serviceName: 'Embeddings',
    geography: 'Global',
    modelName: 'All MiniLM L6 v2',
    inputPricePer1M: 0.0090,
    modelTier: 'Standard',
    modality: 'Embedding',
    multimodal: 'No',
  },

  // ── Alibaba Cloud (Model Studio / DashScope) ────────────────────────────
  {
    providerSlug: 'alibaba',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Qwen-Max',
    inputPricePer1M: 1.20,
    outputPricePer1M: 6.00,
    contextWindowK: 32,
    modelTier: 'Frontier',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'alibaba',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Qwen-Plus',
    inputPricePer1M: 0.40,
    outputPricePer1M: 1.20,
    contextWindowK: 128,
    modelTier: 'Standard',
    modality: 'Chat',
    multimodal: 'Yes',
  },
  {
    providerSlug: 'alibaba',
    serviceName: 'Foundational Models',
    geography: 'Global',
    modelName: 'Qwen-Turbo',
    inputPricePer1M: 0.10,
    outputPricePer1M: 0.30,
    contextWindowK: 128,
    modelTier: 'Efficient',
    modality: 'Chat',
    multimodal: 'No',
  },
  {
    // Model Studio text-embedding-v3 ≈ $0.096/1M tokens (third-party price
    // monitor; Alibaba's own intl pricing page is console-only). Added because
    // Alibaba showed N/A on Embeddings components despite offering Qwen
    // embedding models. Verify on next data refresh.
    providerSlug: 'alibaba',
    serviceName: 'Embeddings',
    geography: 'Global',
    modelName: 'text-embedding-v3',
    inputPricePer1M: 0.096,
    modelTier: 'Standard',
    modality: 'Embedding',
    multimodal: 'No',
  },
];
